name: Docker Compose Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Compose services
        run: |
          docker compose -f docker-compose.yml build \
          --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
          --no-cache
          docker compose -f docker-compose.yml push

      - name: Logout from Azure Container Registry
        run: docker logout ${{ secrets.ACR_URL }}
